spring.application.name=backend
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# This prevents Spring from crashing if the queue hasn't been created yet
spring.rabbitmq.dynamic=true

spring.jpa.hibernate.ddl-auto=update
# This helps see exactly what name Hibernate is using
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true